server:
  port: 0

spring:
  application:
    name: user-service
  redis:
    host: 127.0.0.1
    port: 6379
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
      path: /h2-console
  profiles:
    include: oauth

  config:
    import:
      - classpath:/bootstrap.yml

file:
  dir: ./image/
  url: http://211.115.222.246:1000/

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans, busrefresh, httpexchanges, info, configprops