# Spring Cloud Netflix Eureka? ???? ??? ?????? ???? ??

server:
  # ?????? ?? ??
  port: 8761

spring:
  # ?????? ?? ??
  application:
    name: discoveryservice

# Spring Cloud Netflix Eureka ??? ??
eureka:
  # Eureka ????? ??? ??(?? ????? Eureka Server ?? ??? ???? ???.)
  client:
    # ?? ??????? Eureka ??? ???? ??? ??
    register-with-eureka: false
    # Eureka ????? ??? ?? ??? ???? ??? ??
    fetch-registry: false