spring:
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/user-service/login, /api/user-service/signup, /api/user-service/regenerateToken, /api/user-service/mail/**, /api/user-service/actuator/**
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/api/user-service/(?<segment>.*), /$\{segment}
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/user-service/logout, /api/user-service/user/**, /api/user-service/evaluation/**
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/api/user-service/(?<segment>.*), /$\{segment}
            - AuthorizationHeaderFilter
        - id: club-service
          uri: lb://CLUB-SERVICE
          predicates:
            - Path=/api/club-service/**
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/api/club-service/(?<segment>.*), /$\{segment}
            - AuthorizationHeaderFilter
        - id: chatting-service
          uri: lb://CHATTING-SERVICE
          predicates:
            - Path=/api/chatting-service/**
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/api/chatting-service/(?<segment>.*), /$\{segment}
        - id: board-service
          uri: lb://BOARD-SERVICE
          predicates:
            - Path=/api/board-service/clubs/{club-id}/**
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/api/board-service/(?<segment>.*), /$\{segment}
            - AuthorizationHeaderFilter
            - ClubMemberAuthorizationFilter
        - id: board-service
          uri: lb://BOARD-SERVICE
          predicates:
            - Path=/api/board-service/users/**
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/api/board-service/(?<segment>.*), /$\{segment}
            - AuthorizationHeaderFilter
        - id: schedule-service
          uri: lb://SCHEDULE-SERVICE
          predicates:
            - Path=/api/schedule-service/**
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/api/schedule-service/(?<segment>.*), /$\{segment}
            - AuthorizationHeaderFilter
        - id: openvidu
          uri: lb:https://OPENVIDU
          predicates:
            - Path=/api/openvidu/**
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/api/openvidu/(?<segment>.*), /$\{segment}
        - id: openvidu
          uri: lb:wss://OPENVIDU
          predicates:
            - Path=/api/openvidu/**
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/api/openvidu/(?<segment>.*), /$\{segment}