spring:
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/user-service/login, /api/user-service/signup, /api/user-service/regenerateToken, /api/user-service/mail/**, /api/user-service/actuator/**
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/api/user-service/(?<segment>.*), /$\{segment}
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/user-service/logout, /api/user-service/user/**, /api/user-service/evaluation/**
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/api/user-service/(?<segment>.*), /$\{segment}
            - AuthorizationHeaderFilter
        - id: club-service
          uri: lb://CLUB-SERVICE
          predicates:
            - Path=/api/club-service/**
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/api/club-service/(?<segment>.*), /$\{segment}
            - AuthorizationHeaderFilter
        - id: board-service
          uri: lb://BOARD-SERVICE
          predicates:
            - Path=/api/board-service/clubs/{club-id}/**
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/api/board-service/(?<segment>.*), /$\{segment}
            - AuthorizationHeaderFilter
            - ClubMemberAuthorizationFilter
        - id: board-service
          uri: lb://BOARD-SERVICE
          predicates:
            - Path=/api/board-service/users/**
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/api/board-service/(?<segment>.*), /$\{segment}
            - AuthorizationHeaderFilter
        - id: notice-service
          uri: lb://NOTICE-SERVICE
          predicates:
            - Path=/api/notice-service/clubs/{club-id}/**
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/api/notice-service/(?<segment>.*), /$\{segment}
            - AuthorizationHeaderFilter
            - ClubMemberAuthorizationFilter
        - id: schedule-service
          uri: lb://SCHEDULE-SERVICE
          predicates:
            - Path=/api/schedule-service/**
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/api/schedule-service/(?<segment>.*), /$\{segment}
            - AuthorizationHeaderFilter
        - id: fcm-service
          uri: lb://FCM-SERVICE
          predicates:
            - Path=/api/fcm-service/**
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/api/fcm-service/(?<segment>.*), /$\{segment}
        - id: websocket-sockjs-route
          uri: lb://CHATTING-SERVICE
          predicate:
            - Path=/api/chatting-service/info/**
        - id: chatting-service
          uri: lb://CHATTING-SERVICE
          predicates:
            - Path=/api/chatting-service/**
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/api/chatting-service/(?<segment>.*), /$\{segment}
        - id: chatting-wss
          uri: lb:wss://CHATTING-SERVICE
          predicates:
            - Path=/api/chatting-service/**
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/api/chatting-service/(?<segment>.*), /$\{segment}
            - WebSocket=ws # Enable WebSocket support
        - id: chatting-ws
          uri: lb:ws://CHATTING-SERVICE
          predicates:
            - Path=/api/chatting-service/**
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/api/chatting-service/(?<segment>.*), /$\{segment}
            - SetPath=/ws/**
            - Hystrix=chatting-ws-hystrix # Optional: Add Hystrix circuit breaker for resilience
            - WebSocket=ws # Enable WebSocket support
        - id: alarm-service
          uri: lb://ALARM-SERVICE
          predicates:
            - Path=/api/alarm-service/**
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/api/alarm-service/(?<segment>.*), /$\{segment}
        - id: openvidu-http
          uri: lb://OPENVIDU
          predicates:
            - Path=/api/openvidu/**
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/api/openvidu/(?<segment>.*), /$\{segment}
        - id: openvidu-wss
          uri: lb:ws://OPENVIDU
          predicates:
            - Path=/api/openvidu/**
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/api/openvidu/(?<segment>.*), /$\{segment}
