spring:
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/user-service/login, /api/user-service/signup, /api/user-service/regenerateToken, /api/user-service/mail/**, /api/user-service/actuator/**
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/api/user-service/(?<segment>.*), /$\{segment}
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/user-service/logout, /api/user-service/user/**, /api/user-service/evaluation/**
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/api/user-service/(?<segment>.*), /$\{segment}
            - AuthorizationHeaderFilter
        - id: club-service
          uri: lb://CLUB-SERVICE
          predicates:
            - Path=/club-service/**
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/club-service/(?<segment>.*), /$\{segment}
            - AuthorizationHeaderFilter
        - id: chatting-service
          uri: lb://CHATTING-SERVICE
          predicates:
            - Path=/chatting-service/**
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/chatting-service/(?<segment>.*), /$\{segment}
        - id: board-service
          uri: lb://BOARD-SERVICE
          predicates:
            - Path=/board-service/clubs/{club-id}/**
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/board-service/(?<segment>.*), /$\{segment}
            - AuthorizationHeaderFilter
            - ClubMemberAuthorizationFilter
        - id: board-service
          uri: lb://BOARD-SERVICE
          predicates:
            - Path=/board-service/users/**
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/board-service/(?<segment>.*), /$\{segment}
            - AuthorizationHeaderFilter
        - id: schedule-service
          uri: lb://SCHEDULE-SERVICE
          predicates:
            - Path=/schedule-service/**
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/schedule-service/(?<segment>.*), /$\{segment}
            - AuthorizationHeaderFilter