spring:
  redis:
    host: "{cipher}AQAbHK9dcvo0R8pVBTb332LJXp7Zer8EarGfgkwieBmpwcjX+5OJLFVhQwi+QkfTBMYx9i3RLGG1bdbhJ14qBHFmcKytxwidcn3vbMwn0u4mc7X6wf194Vn10UqgEJwq/rpEQrP0dBRGNmND//apbiUmi29M8nn18YI9CNkVfssKZ+8h+yPGJdS38KIAc1OCrDe9Qcvoe6zXOUj4rdpE78TePKF9+3QSGZoKt4TvQ8XqrpuSsGDXkbarVf0HxmVSpiPKAEHApAPExqNcxbOW2cMm1/63mG2+/eUuiRROWNguNjdFvB3ghN1P8nV1nh486MT6wrsEGY0A4GIIBuGlI//OoNM4D9I2Sr2CJjB1blg5Yp4fsbqSSn3yb5PsOZNMnak="
    port: "{cipher}AQC/f3twfBlaoJ4/vYKE/J0/EC3HOXlA48mtsEfOoac/9VtWkJUvTm7NSZZKsGBSa7QwI4upjxJYtiLjpUv+sPaIAMCwtFasCpoSFlYeN9wbhRB4Btm5qwU7Fnm89kUe0a5FHTDqAkIAe50/2zhyKh17jZNOR8KTy6ePLgRh6aoqBM6GB00QjkyGDBeIpOx+AALbum/oUn9EKg3zhygoFtxF25JllwoxfSy5sISUP2fMS74xqKJEMrN/lHfo8Kv7vncBP4U+rQffBKWDlDAc9MVQ0zL54ZwnoZlHMD0n0I+d0+qZYGSnNsM7xeDZA7vE4HiMqesEIi5vPhgwZN0w4qJGNWQaCceSAJS6DDLDwc2x3BAhykcvQgIzj3Lge+MXvh8="
  cloud:
    config:
      import:
        - classpath:/bootstrap.yml
    gateway:
      default-filters:
        - name: GlobalFilter
          args:
            baseMessage: Spring Cloud Gateway Global Filter
            preLogger: true
            postLogger: true
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - '*'
            allow-credentials: true
            allowedHeaders: '*'
            exposedHeaders: '*'
            allowedMethods:
              - PUT
              - GET
              - POST
              - PATCH
              - DELETE
              - OPTIONS

management:
  endpoints:
    web:
      exposure:
        include: health
