access_token:
  expiration_time: 3600000
  secret: "{cipher}AQCZdZ5k+hkmDnSJmQqrtBD7900eVpa14AYoF/c/1KHflfReQGmmfAMyf0QQDXLDwd06zHiGD9h465gLs7KNzrnSqhX5uNPrV/L1PSwkTrar1wdPjw4Ejm5D97SRwDcJVefAt7lGerNGRat4PevNysE5gEWUbD30fbirHSmk0swvPW5FbxwSyMCVI/C5R+abeqLVSDwC3c+3mDRvQ2SJSWTzt+7anQuJEgPnShFw1ceyj4V13MPmVL4GGGS/8FyGn8cOXxyNZgWhMcygueyMSrhwFU2BkH4wL44V/vyUSNTyM7X5RzEeKHzxWlfNMiLysWtwp8pgqfeUZ3zb8Szg6vagSQo2ea3R9wneeWnP/zphDbuUg09V1Xm0rpL2SBcCeGg="
  
refresh_token:
  expiration_time: 864000000
  secret: "{cipher}AQCZdZ5k+hkmDnSJmQqrtBD7900eVpa14AYoF/c/1KHflfReQGmmfAMyf0QQDXLDwd06zHiGD9h465gLs7KNzrnSqhX5uNPrV/L1PSwkTrar1wdPjw4Ejm5D97SRwDcJVefAt7lGerNGRat4PevNysE5gEWUbD30fbirHSmk0swvPW5FbxwSyMCVI/C5R+abeqLVSDwC3c+3mDRvQ2SJSWTzt+7anQuJEgPnShFw1ceyj4V13MPmVL4GGGS/8FyGn8cOXxyNZgWhMcygueyMSrhwFU2BkH4wL44V/vyUSNTyM7X5RzEeKHzxWlfNMiLysWtwp8pgqfeUZ3zb8Szg6vagSQo2ea3R9wneeWnP/zphDbuUg09V1Xm0rpL2SBcCeGg="
  
# # 접속할 수 있는 IP
# gateway:
#   ip:
