access_token:
  expiration_time: 3600000
  secret: "{cipher}AQBzW3DOHOW2ic1F4u5NbD6okETNHnZ5YAihQaPGJgiCEUK7ZE1i4H/CBwIdKWg46o531bK83hnlEWEKlXq1E92T+MAL7mvNWtzGozMZdzLqUdj3B+zAXqJv7pG4dkyoY1qcxpmfJog4A5P8OANj19rza2y3BIkRWvij5cvqO+5F+fpK3st25FaeitDXnb6DlFtju69mWllpnV/YFYRXrzz9ipWaRU7Bm39u7tK8LY0Efhoj9AtC+gkKjbN98j155XXwkTR18DLc1Ngex8mKRS+KFT8paKC5FlZWzHDb/HahtEYAyaKYSFIj1zHcV0y64VRQPrqjWVrC6ofIFE+HHYnzpg4sQZ8njzHaXG2cQTorUuV7qdLniqytQR0wHfnwjhWPa4OMVuonxg449CyEfRz7"
  
refresh_token:
  expiration_time: 864000000
  secret: "{cipher}AQBzW3DOHOW2ic1F4u5NbD6okETNHnZ5YAihQaPGJgiCEUK7ZE1i4H/CBwIdKWg46o531bK83hnlEWEKlXq1E92T+MAL7mvNWtzGozMZdzLqUdj3B+zAXqJv7pG4dkyoY1qcxpmfJog4A5P8OANj19rza2y3BIkRWvij5cvqO+5F+fpK3st25FaeitDXnb6DlFtju69mWllpnV/YFYRXrzz9ipWaRU7Bm39u7tK8LY0Efhoj9AtC+gkKjbN98j155XXwkTR18DLc1Ngex8mKRS+KFT8paKC5FlZWzHDb/HahtEYAyaKYSFIj1zHcV0y64VRQPrqjWVrC6ofIFE+HHYnzpg4sQZ8njzHaXG2cQTorUuV7qdLniqytQR0wHfnwjhWPa4OMVuonxg449CyEfRz7"
  
# # 접속할 수 있는 IP
# gateway:
#   ip:
