access_token:
  expiration_time: 3600000
  secret: "{cipher}AQA9ixAC/3nM91eY/NrKUkn4Cdg1uHF5KqWlYOExnZCsUsCdmG/w+2i9NUvpmdJgKe8AYJbvtqZ2qpX+RsAlTHGtLZg0ZA30RfuS5JDZ87cGBATTjzyK4iJx4ZSQcoW1GT9l3uvmm0oOn8YUQDD/dsuPwz75GNn8qMtUXOtapAwlKQkYEtMRD5aeTkaju/F9/ERxbgpfNXQI0W+5lPEerTYv/s2ErVO8emg4dhCyc15ee8dFpS+LbpK43UhoXNRSasdo5SyfVjO60/TKbHqjlcZIwBLO+6vqfX6M/xYmjvAZE8LbCjbcDKKH2YEux8m/anQC0FR7Mg8j3AFpcHrLHF4ta5TJd1s2+fyQzjLpBpOxI9WjNE678b+pXPr+zwHO5qwfQytHrGxTkVS/ptjxj6FOQaHSNjCRrhrVCjcs319ZK4By/5EwhTeEyAbympckXQqz5lutvNxRNgvGhtOVD6digv8tBdEHQdzvmlgmBVS6bs/HOuR/FZoLYHlGAWJ9kmrejLIf3meFP0idw/LADcFi"
  
refresh_token:
  expiration_time: 864000000
  secret: "{cipher}AQA9ixAC/3nM91eY/NrKUkn4Cdg1uHF5KqWlYOExnZCsUsCdmG/w+2i9NUvpmdJgKe8AYJbvtqZ2qpX+RsAlTHGtLZg0ZA30RfuS5JDZ87cGBATTjzyK4iJx4ZSQcoW1GT9l3uvmm0oOn8YUQDD/dsuPwz75GNn8qMtUXOtapAwlKQkYEtMRD5aeTkaju/F9/ERxbgpfNXQI0W+5lPEerTYv/s2ErVO8emg4dhCyc15ee8dFpS+LbpK43UhoXNRSasdo5SyfVjO60/TKbHqjlcZIwBLO+6vqfX6M/xYmjvAZE8LbCjbcDKKH2YEux8m/anQC0FR7Mg8j3AFpcHrLHF4ta5TJd1s2+fyQzjLpBpOxI9WjNE678b+pXPr+zwHO5qwfQytHrGxTkVS/ptjxj6FOQaHSNjCRrhrVCjcs319ZK4By/5EwhTeEyAbympckXQqz5lutvNxRNgvGhtOVD6digv8tBdEHQdzvmlgmBVS6bs/HOuR/FZoLYHlGAWJ9kmrejLIf3meFP0idw/LADcFi"
  
# # 접속할 수 있는 IP
# gateway:
#   ip:
