access_token:
  expiration_time: 3600000
  secret: "{cipher}AQA2Osc40D5OL07nyVPWgKHYdsPKvGpCftP0rWk1r/QENL9BNaoNolmsz4UwH9Rkrsgo7IGK+yhqlNB3HjyK7E68PeRHWWRRGNRLh3uCx8UZwMNghHBkOK7JUJgiI9bjLg7TYRH/GqvNjd9JzQHo+IE+pImar2NeJOZlaAuiqoYg3MiwxBVJtXuXkeyTHoJTFdsgwmZXDiOfHh9+jmdUCNkrgedmbC3E9gA0QzXYP5LTN5dnrgX+p/Q5bGKkTsNduAWPHxCQY08IvOEX6t13O9wyDKM2oxl55IjDVVkkAMElkYzF7wPzFRtsPKwLVYJTLifnDO9h4btAtq8H+7aimxixcHJYEiIKLS2bv8HO70SFlrDmgXCfikEVQPuDtdI1rHEM12qX1s/AC9FghxuUxmKwgXRtRwtSGH8j0QanBiUQTILr1RJKn0120I7Tm11ydFGEB85LkBKqPf35TdMfVeUq"
  
refresh_token:
  expiration_time: 864000000
  secret: "{cipher}AQCOSHnmMA7Q/Yak+19aIL1crEZnndXthEK105L9DwLF/O3ze8X1lwwa50rIN9fQmSCbEiE8mYp6HJ5AQKQwqH2x9iio9ecDXpE9kWTAVTSVvq7DaQY7NzFRCq/kScBwYX6p24HhsT4RMnOMztvw8oW7OkaeVM0ECGbe+Vwj8QwlLM/nIya2LQ/tBCArC7ECjvyU5+DJHhsSA9eMH4slFwcfMAc52xNZxznut4W4LjLHtGoskC0Dl3RRNPQTSxRjfSA2gONLFPGFttJIxykKprY/hXYd3XFsGvqKKSwBvlw61HMQRzL23yi+aoegWtOfRy8kN5guVOPRUgH6Hm4QY/jcUyKRaS268IlTm+g+01fyAX6t0n/bT6CzG6clbkmJLQflHNrrTKUu2JaumTOsL5fFRLffQ/gPLvRGR3Sk58RBY1aC0ilKJWOt0T/nXSXXFaj9ZSnNipYyvUjVqEUPA7YT"
  
# # 접속할 수 있는 IP
# gateway:
#   ip:
