access_token:
  expiration_time: 3600000
  secret: "{cipher}AQBb3MhX+MTw2YxCtJ5JPhJEQFNFvCEsNV9aSggrLKSZ9B+iU9raQWaZ0s7SdbSZWnvY3xabhhLRFXcefI+MIwtlaf/IUCzfvgLLC5sLj7clpqVYm7WPcJyYTsmz8nYq0I9SA225zJKiQQRSpSmzmRdBMTbRWUGpzH2nHj/js0MMeJ2gqxdjf0mY4e1L7L4/9ydIMc69uYgkKhs9wr/qYM5vw1I6qlFqCLsZJQEpqVEBv7XrrN2vdJ1JscOrnsu6CUTFggkB7PnCeOQKsJppVdZOO+uUzSponq5U7eaV+beCiu7f+BKbdH2meRDRRjKlBr1Sv9mBU/jSjLBP3Dij5RxWXMSEvKlbVneozrWJa3waUtQm+47UqW5Bn8aRmEFZ3/IHb3T87mj0rH87ULUk13MMvIFozMe8PCPkjxbccVMZS6ZAhnI8QDk98XV/d4W5ZEo5/Zc7Cu3Nx5ozY+jz+D3g"
  
refresh_token:
  expiration_time: 864000000
  secret: "{cipher}AQA3u6qKZngVRKTuyedwH81tvBVinaEMBdgFHlXdK8ngkvFEDHlNm59Hf4yiJAMudc9OxzfXzIlKLx56ID0rhvt+bPE/lDG2ValbG4U6wvqHL4fVFhCmerKVxqO+S5UauBuheVB0zEb7xoHaQjxJD8WOGZHOSIM21AdO34WX6weJ3ViwCbORjZbb2O9aYliLVXENUMZcOdnkN9m2Y+N31UINW1F2e0IvElFO36KTL2Fy4LTAN4k1E58laF1Q6ZZXoCa3ao+Zx8EyNio4DwqYRYdG8itUCKNCyO+WbcQQA6SgJgHR8sds8JEZ6sMtCpzNsRAcv/qFn6O0aBIgRDa9K36pd9HseZ7x/jr2PzCIOHbBrLMqiXlCmsjsPv4mg29+kmsZJBRkQG0d7CHCrg/1Jk/hKxJTintwbjkERar+u3qcTJYvvGBJQerMRI8gq+UlSh1ioivw+QQEau78EMXFuOwX"
  
# # 접속할 수 있는 IP
# gateway:
#   ip:
