access_token:
  expiration_time: 3600000
  secret: "{cipher}AQBu8H94muqEEUL+rdN0iGtwZMPf7rEY2XoVYPj350lT1O4r667KTsNDP4kjijd3VY5wiqZJodBij3H9ab91Op7au6+tkcPA9J0b6+HtDUXEC/Dw/qRcFRxwuCk0W7arKXjdfbSXhR4HdMdVyfhNrd7etbWbs5Bicgnj10XHBvJTv2eO0F4mdSH4bf8s5M726TBn5huK28KWN+6xLEe1oeOWYtxROxUccpGyhkcuhWn224xQtcmHGSK1PjzrIGXqlO5O2PhISf63DYdEvVgMGFz6U+78lrHnal8b2tX2KxIkc+LdZx89vTPVtQ4JbiKvte9QpYhk2sH5JAAR7/7xTFEIylSNyuj+IN1rhEz4Qt6VfhUmxAorimvnITbwDo5wSWaoxvoa0JKx8zGsxqMED7Lf"
  
refresh_token:
  expiration_time: 864000000
  secret: "{cipher}AQBu8H94muqEEUL+rdN0iGtwZMPf7rEY2XoVYPj350lT1O4r667KTsNDP4kjijd3VY5wiqZJodBij3H9ab91Op7au6+tkcPA9J0b6+HtDUXEC/Dw/qRcFRxwuCk0W7arKXjdfbSXhR4HdMdVyfhNrd7etbWbs5Bicgnj10XHBvJTv2eO0F4mdSH4bf8s5M726TBn5huK28KWN+6xLEe1oeOWYtxROxUccpGyhkcuhWn224xQtcmHGSK1PjzrIGXqlO5O2PhISf63DYdEvVgMGFz6U+78lrHnal8b2tX2KxIkc+LdZx89vTPVtQ4JbiKvte9QpYhk2sH5JAAR7/7xTFEIylSNyuj+IN1rhEz4Qt6VfhUmxAorimvnITbwDo5wSWaoxvoa0JKx8zGsxqMED7Lf"
  
# # 접속할 수 있는 IP
# gateway:
#   ip:
