access_token:
  expiration_time: 3600000
  secret: "{cipher}AQByanJ8Y+ykasQcLruFelcPSutN5XRMgfQu05xhKEU1IqAKEa01xNEhD7DPzNnLDe33BOPPFN7PhLOKv2jA25LuYMzIwl9Hm195S8oYCWD/ll6S84kbQTiaSmHCQt/Jr4FYjTZ3Qge7H7kyxna34MJafvPcZ5UH3B+2eu4pplMTWHVxZR13XwOsUe4aw+OLom4w5rw7pGDDl+YUWDQGDuQracn4Ujcl4i2qg0z/qa88QyAZEcOzgAHgi8qYX564Vbx1Y/J+ksiPGzVlld3UCMjZvdW8a1+cl1SdDSCAyJeAxjxzsazF9+blXTtS6ULseOD+pE932mpMJn9VSYp8ZHUP6lafI6v7BZau//7DdMokQFH1Ba9s4aJeUTEb95o31ng="
  
refresh_token:
  expiration_time: 864000000
  secret: "{cipher}AQByanJ8Y+ykasQcLruFelcPSutN5XRMgfQu05xhKEU1IqAKEa01xNEhD7DPzNnLDe33BOPPFN7PhLOKv2jA25LuYMzIwl9Hm195S8oYCWD/ll6S84kbQTiaSmHCQt/Jr4FYjTZ3Qge7H7kyxna34MJafvPcZ5UH3B+2eu4pplMTWHVxZR13XwOsUe4aw+OLom4w5rw7pGDDl+YUWDQGDuQracn4Ujcl4i2qg0z/qa88QyAZEcOzgAHgi8qYX564Vbx1Y/J+ksiPGzVlld3UCMjZvdW8a1+cl1SdDSCAyJeAxjxzsazF9+blXTtS6ULseOD+pE932mpMJn9VSYp8ZHUP6lafI6v7BZau//7DdMokQFH1Ba9s4aJeUTEb95o31ng="
  
# # 접속할 수 있는 IP
# gateway:
#   ip:
