logging:
  level:
    com.example.board-service: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans, busrefresh, httpexchanges, info, configprops, env
spring:
  rabbitmq:
    host: "{cipher}AQB13T577ind8KCCFY1U3DqQnJ5LKBR4B4wehYnGO0ucfh4vG0dEd1UEUJiL3UzCs+u0V8O6pzHn3w0TGL+KVFp629Cl+sGCftGztlKBVcShKxF9zEavo6e94/mhg/8SStrZvVG360eEqapwfK/EOBFcr1s2wI8IrcypooWPxmNzTYNJMfkwufitZkxXSPt6T/R63tEqwzXz6+C6lNkmB1q4XW7XmvyxduOHPNpMJQbsWFKzzVMZxruk3NM41ESeIfwKZEeD2jSO0p7vNrlbSa2hNcMP7ev+rU+DE+rMTlcqR/apaLIgLkNKMivZYtwQxZp9GU1qk7qowXM4/l/J2iYY4PEB3N11/uBfNnkVPbwE9iV1OPSL9t5u8UYwHeVr3Sc="
    port: "{cipher}AQDBKNvT7WUWI5ZuQacql0FdAkH5EBsR3aB6AXcyXDaCaHOqONyvNB7oI0qh8V4rjTZfDxlRePdH5mcceIGbe+CHm7ZMGOHXXdpxG1Rocno8+BL6VUThd0Rq4u3YhixsfdPb35A5w93c9JJKcqrrlh7s5AWQUSWWN1Ojh1QQT3O3k/+xGduaUbLTqHZFcDXH4FnZ9auKkmqZtRVfvsJ+Z16ZuP+tbD9ac3UUHm2wdrXWbHYzRMeliS42ylto1BvVIDNPnF4r5JMcCEna89hVTW5HVCVfDWtTbyHyaYT+fspYmCVyDTLo6Gtvmfs5qhyRrjH2DxHdDzqSDP1YDCjSTD0fmDgvkJ98sv3PQR456amKzjx2PxC5tQFv8DRmS9h20QQ="
    username: guest
    password: "{cipher}AQDqXGjg4tH/fFlzIZRB5nnl2I5OqbhWx89He7hozm6qLXbTviXPpk12yDQTiTveeW0PnH9PsMyLtcZaoil9PltC3rcYDRFJ/u3onpZ7jWTx1iHqa5Qruab5gCC6ArHr64HkqGXTEkl8yy7dnLPipiQNCnZTsJag4Q0TdC9nlKTlE8wxcMuko/9vL8exRb3z2KveJrnJRL2NMRpy+ByTF1f+S0dVwOInweVKpYwOkfORTYfz56N8ooqAkK95yDtJlVSXsQXpU0/wpqwCCzDYKLpzUZKwIqfGF8KIoAlf2TQcvmScrX2RdU+YZWYnU4g33dlEE7Ds9y6gzNDQ0MX+mZvFbL4qq9jXy+cW5qOhv7BFNlBqtAlcRatRr+vN6ksHSRA="
