spring:
  datasource:
    driverClassName: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://211.115.222.246:1019/board_service
    username: root
    password: "{cipher}AQBl27T25pwaioxIoIb4Er2pX0E1+sIaJXRYmJjO5SNuEiYbNLvCoPZwMFmKXdskUBnnUTDhzqVo5Hxe0i2oTU3F7u1yWAO+Ynvts+JFeKOHAuNWQs7CeYSqbtWUQ2a5uMDaBhudMVvXB9C1hS8z7s/lD20l6NOQqE7fq0ywNsZhMA4092sW5wp0rcrVD/S563N+3tUwUuXjHT0ZHErDW29U3vy5soJzwhAh9wbnsapGdL9qkBWX8JjZSmceO5GPA9nBIGsb0dvmIBGs1k0ltSHtB+y0pr0YdUpMkWXv9ehqXU6q1zE5MhegMWm4bvvuh8BBLNlqhBz3kpQJ12td/Y3FmVFcGV+80Qhr6iecun1TXay2iIZUbV7X9ByPXTl2WZo="
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        ddl-auto: create-drop
      
  rabbitmq:
    host: 211.115.222.246
    port: 5672
    username: guest
    password: "{cipher}AQDSrvg0mJsIddgPsLUP9JHnOD1GoqNUxqQKH6AOE9+Ppwb7dJVhcY2wEAdTGN/QpEtwo5olmdInrScG626i8m7/9QB05loFc/bEcpI/pcN5Cfv5KNqwNFMPeA0aBc8Cvd11uuOWNy8a2gnW3LQo30SNIAfDRAOqyavELkZUmv3PKNAFK2didrIeH/Fp4LCvmpxCih3JNjOll64HgDGjP0YJZqgRKio6XNAAfXbiINV6+4k2neMe4xUrfnx0mR65HLFbP028kFCjsE4QGth36wN/7o5zd7Jbn118FiDwXhjVdzQZtPeMopoqciiGI5g/9rRqSSuoWmYa8xMYpO+BJJYAyEKg5CEOb5MVtl/Nn5svrzTZfLq9w7RqLvSbJT0lDvs="
