spring:
  datasource:
    driverClassName: "{cipher}AQDaJ0YIo/sL3WXxItJLspRUPYBnKCX8gKxbWdv2OcOzOZvM+TzyFFZOzQxzYzcQ8oV/Sdqz5fdYbLYXjeBvm+dP3+YihKuzPsZP8xBinbc2MIwtR/LmqbQhdVyZfeeNiTSU3qZ8A/oPsh3K+1oeQmgoLKPcgyBixUq90K3bq7sdXzByK6rstdemtXqeUPJM+sF6LKzFLR6UTJKNL5h69J/3K1ITy4q8mPafIeVeS4kKqLCduJ0O4jfZXdFzsNms7jZ+Bdf3G+hejMLBrLIph+WZOB/4evJ1+apzYuT1V906aLD/SJVPwIBzIuo9NzEyoh06BloSkjUKAnqcecb2yr1fgTiE2zIRWZ3qPeQJUDoEaUS5kMsYw5giP+aHTcGSNwcKlmUucSJoSExk+wCv0wSB"
    url: "{cipher}AQDgcXPyn5RoerwJHpiJu6xqwhcpal/+tfe/0K9sKzGx6ET8WL5Zq4A0UVrrtJg1sCBKqGaCliSUSlrPdlm14gWdtGU+Rn5O+jJt8i/9gK8brozcWsx2rWAeQohavgIxeE1hJAXcHMlG7smpu+qA3ec9UHA3MRVm5df1AmPtEw160dLmEXx6BuzTSzi+3fLY1+P59NwCPQKfS7fklVJ2sWve/p4jsDzP+eu0bgVtNKVUm7kXzcTmq7njkJF+KV0ipgPFPB6IYnJe7mrZr/c8wuViZGT6F2y3VTd7tXH1plwtrFR8No7rCwb3Oc1APMdPowiIZIhYkQS25cU/ZedwYAzcrcFLZvhLe5u0T80zlTxPsBtAYMJvb47gGGYolHefoD6r+iO13bIihJzgftRR2q5SCVlC/VsQ1IIpIafbEEZ2wA=="
    username: "{cipher}AQAvVtEL1Wr/PonK0066xNu/KNjBrNRrJQ12Ka33wk98L3H9rxwh/x7RAvTGphK9VjjbIm7Aj1IrWHRJeDEvDQLVRUVJ1oIGqfcVUZt087HKlm5dugIqpeCONJK+FaubQTMO5/KKPPGMZEMuRle9ur2wIVmfm+0NNU0hk4nxD+lep201AzrKGUrdx7xHTT9AfTqtCSZaD5/aZgTfKCaIXxK2EWVYS+iOSFlNtAfv2L1qB5sZ0jqmKf3n4GJrxXEiZFB6dxMRDrieiuH8qesa89GXzGSfY6wT0aBRkUC0b1FXX3zR2wM9Dht+zT92D55gKfnn55MWX7vvN0xG7Y7bxOEgsz4MgLv1QQmbMo/BQr7E911C1vfEKlYXCQpWMPrXWi0="
    password: "{cipher}AQBatMFoS7Gk8zeH/yDqh17exaCOb6vF9lk7H7/rhtCx05bdUBdbukeO1yk9ATSRg8qZciCY1aR/pDSVayqQmF1qrmXLFC4odwTlI/EGIvn1EiBefLbxrk+5WobAnC1bEKmxpYXBm4u7X/y7L/NE5SpKEAhL09py8tZv3IDIbsCK3NFACoUqb+G02nYSNnsI5shivkcElSW1TrIEiiTgQqioA/Drj8rXaWzgoDZ8SoRVZgeH4APNKooW3FMjkLvLEApFnFkR9IRPhUy77zQB/gwkd/3Xb+9igY2jAR1J1qO0u3Oe+yxtgvTTLBpk8tLsIFM0cpwG+vq+6w+x1NGLdhxrK+39BUMbod/WqWfN6TBRXi90B1Q8phI2BHOOeQaI+k4="
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: "{cipher}AQA9G+89tJBSbPFlGciphEBcNa5MpD66RAxy7lIBtEWDoSqIOY1IdXy8N+WTEcVItgg4Xk3UT5qRVnXngwn1e2BuezX4r3XXdVpZbz4TM77gwZ5cYPSTxqNImp18IhLUtko9WUexs0Nobcqu2ImYl8vW1OCLcblGSlaY8CSc/Z8C2OGQMhBFlV2vcX/45yZwWKRNyrN2GQyp+34X2S+cFgBxaZAqFpZYPaSCTpkfACyClgj7kXPHnDVwgl5ObBSYwYtaTDbsVbPq/xscjxwO7SauFllayzTQyVKuzby+Jmave7/srSblCcofB/K7MhnXqACdatzjkB6fK/ugKT+OQEJH7ejIsnfnZTMaktK9HdVP0GdqEcPaIbzO0cBO5mGz/rbRZikkBQdYwxh4ZUl+B/cMjXedSUEg5rAAkh8dKvgPvg=="

logging:
  level:
    com.example.board-service: INFO

management:
  endpoints:
    web:
      exposure:
        include: health