spring:
  datasource:
    driverClassName: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://211.115.222.246:1019/board_service
    username: root
    password: "{cipher}AQBatMFoS7Gk8zeH/yDqh17exaCOb6vF9lk7H7/rhtCx05bdUBdbukeO1yk9ATSRg8qZciCY1aR/pDSVayqQmF1qrmXLFC4odwTlI/EGIvn1EiBefLbxrk+5WobAnC1bEKmxpYXBm4u7X/y7L/NE5SpKEAhL09py8tZv3IDIbsCK3NFACoUqb+G02nYSNnsI5shivkcElSW1TrIEiiTgQqioA/Drj8rXaWzgoDZ8SoRVZgeH4APNKooW3FMjkLvLEApFnFkR9IRPhUy77zQB/gwkd/3Xb+9igY2jAR1J1qO0u3Oe+yxtgvTTLBpk8tLsIFM0cpwG+vq+6w+x1NGLdhxrK+39BUMbod/WqWfN6TBRXi90B1Q8phI2BHOOeQaI+k4="
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        ddl-auto: create-drop

  rabbitmq:
    host: 211.115.222.246
    port: 5672
    username: guest
    password: "{cipher}AQAOpNa4kE1/0SuIdsJIzX86GefXTeuHo8hEUlcQ/pMb3RKu+P98RSXsslRoNq5iaL+yl87whYxj2PeKY5W3rxN3d3bipurOE4udGgEZaUj61xXIzpZOmfhUI6lHjfpTtX9ln7u6U0WdNCaXVwYYVMsEhBYlpPFg2KbhHfmhXREcUI8l0Fuy6UOLhe1fsHXXi7RXoRGKclfuUtnA8i1Ipo9E8uccybKUSaLtmIqNLVTwH4wQbfb2QnjBuYGEzMxD0piQ+Pizbn6ow9bH0okj1+u+GbDL0UZEpsl04cecKDN06/to3x88a7GNsG+/BGxRWKypAiuUl5HiYQfS1qZc9fHMhB+9YoWyPdXGk2M8BLp7ewLe6uQBruSxXpZ1uRCQKD4="
