spring:
  datasource:
    driverClassName: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://10.1.1.45:3306/chatting-service
    username: root
    password: "{cipher}AQBrN2qTBBb9dL+42DX605ep6StbQcePB1nVT0N1e2XOeOM2/9/xOKt1RZ6bygShOAblTtcqCIJrz3yJgnH1N4ETsbs5vYrUYRXrDyQysMbpqn2kJSZyYNrGbvRvYPTipZtybdn4wv4/L+TMpImG3JN7173TZjl69rKMsVtybT4TRwEiQ97z8dtCsLbQiRsYmDoxX7HlLXIqLz1WiV6CnXNegjLIPf7iVHtkcCExpHxE7y3tI+RIQ8xzzdVRjtugogSxbXM0FtLUftUZYAYPGFsgg4Qz6i086CtOWRGynXtFPKorW/8rt+Qz9q5EYVUa6igrr1jC7UD5hU5WNIeyLFF/QSyJomVPvpHG9SXA4Xd1XxZ4LgA61nMQiKcRgFa8whA="
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
  rabbitmq:
    host: 10.1.1.5
    port: 5672
    username: guest
    password: "{cipher}AQA5DUta/Mla91e8irJdYFg5rOr1ldXshbql6WhJ+H1LDYvUqwJmmPhU8nzrtiluafrJZF+El/Glbxkgfo6yrmo2MsZkYlCY4g3hCQh1DMHO36dPIvbJaz6KIAxtsBG4wqTEXfH/zux/xWVo+LZvRy1akGui6P3tDb2xaqlqZ5dJLk2IA/M7Ji4fCqPmB0lr+QM0KIhqnSD+nKMb3fep5z7nztARgjGNaiTYY8RLbBvpUo7r76rQt61FopeIW0beq/IRWA568t3e9Z31oJB6tJfqzkA3Ob1In8T861jO6HK92XJPijMfajpi3Udafby97u0VMeCjyV94dPZ+9shu7mPt/ldRQnv5uWoQmIWDr8qEDPzteHI3ZMyqO+qc0lGrcCI="
