spring:
  datasource:
    driverClassName: "{cipher}AQDaJ0YIo/sL3WXxItJLspRUPYBnKCX8gKxbWdv2OcOzOZvM+TzyFFZOzQxzYzcQ8oV/Sdqz5fdYbLYXjeBvm+dP3+YihKuzPsZP8xBinbc2MIwtR/LmqbQhdVyZfeeNiTSU3qZ8A/oPsh3K+1oeQmgoLKPcgyBixUq90K3bq7sdXzByK6rstdemtXqeUPJM+sF6LKzFLR6UTJKNL5h69J/3K1ITy4q8mPafIeVeS4kKqLCduJ0O4jfZXdFzsNms7jZ+Bdf3G+hejMLBrLIph+WZOB/4evJ1+apzYuT1V906aLD/SJVPwIBzIuo9NzEyoh06BloSkjUKAnqcecb2yr1fgTiE2zIRWZ3qPeQJUDoEaUS5kMsYw5giP+aHTcGSNwcKlmUucSJoSExk+wCv0wSB"
    url: "{cipher}AQDCG0DFRRVLLRdyY94R5A/Y0sOj3Cop2sbj27WKTHQXqvmyNLzvo7PGYxGWMxew7KLl7+GiKfAMm1bmz6H3dRlibvrQ09HX0emL4gJwgZ6iA7CcdjinsAOxEPKY9Tbjo2FG0RWm+LMp4orEMcWz+aZBK77E70s358HwvC1LrAVNyHHdhtTEEbBUpTCtQTUiooMKgll2g7JUK+mzr7Mdv/7pI2D9vJbBaOmgLisUNPXiMUiXCGZqQFzwW9qJknObZheNG5KrSmHCQ34WkmyoeB0j7PWEtwsQDXxtNCxXccQjWo/2agJz5lJ2aO9JLMu2W+vhjI2rczi87UewMOZU6anvOjVnlT/J3vqBR05cdoiq/CrFtEmPyEGZMp/SPe74UFL6NsVjCUReJqQwzmlHx0uDava3Uw3nqAftn5JIbGg77A=="
    username: "{cipher}AQAvVtEL1Wr/PonK0066xNu/KNjBrNRrJQ12Ka33wk98L3H9rxwh/x7RAvTGphK9VjjbIm7Aj1IrWHRJeDEvDQLVRUVJ1oIGqfcVUZt087HKlm5dugIqpeCONJK+FaubQTMO5/KKPPGMZEMuRle9ur2wIVmfm+0NNU0hk4nxD+lep201AzrKGUrdx7xHTT9AfTqtCSZaD5/aZgTfKCaIXxK2EWVYS+iOSFlNtAfv2L1qB5sZ0jqmKf3n4GJrxXEiZFB6dxMRDrieiuH8qesa89GXzGSfY6wT0aBRkUC0b1FXX3zR2wM9Dht+zT92D55gKfnn55MWX7vvN0xG7Y7bxOEgsz4MgLv1QQmbMo/BQr7E911C1vfEKlYXCQpWMPrXWi0="
    password: "{cipher}AQDpfV8W/W2m05X6qMf2N3zyWwV2imgKCuBrePMOJ6WBQmRVC4BzyVjnecB0CiZvrB0aDwPKGfRpmKbkPDl2qXWrX0HD0SnCO3E+R3ZDv4o4pxJAH3XGDkDbUDAoRieo66KLqkCkrjbgbNiaDvrRvj6ZXFqSJwP58oxHs4xS+l+Dv0dSQr2jg16NdZc1cd3UhVjSARcMuYTt1K83tBsGJHwPL2Vf3KhiHgCZoVJVesFvQheOTSy/r1GaYiy0G6hL8xnstBzjzSby3IT60sa2kiDTlPJF91UucxN3vT/a13QVgJMMziXVD+kPkwcMIVVTCesDSvmOquCzXYmZG8pkJm/5yYg7r8S679nbm5h5iMG+2f3EKGmz5oqSsjuXFGUdW+Q="
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: "{cipher}AQA9G+89tJBSbPFlGciphEBcNa5MpD66RAxy7lIBtEWDoSqIOY1IdXy8N+WTEcVItgg4Xk3UT5qRVnXngwn1e2BuezX4r3XXdVpZbz4TM77gwZ5cYPSTxqNImp18IhLUtko9WUexs0Nobcqu2ImYl8vW1OCLcblGSlaY8CSc/Z8C2OGQMhBFlV2vcX/45yZwWKRNyrN2GQyp+34X2S+cFgBxaZAqFpZYPaSCTpkfACyClgj7kXPHnDVwgl5ObBSYwYtaTDbsVbPq/xscjxwO7SauFllayzTQyVKuzby+Jmave7/srSblCcofB/K7MhnXqACdatzjkB6fK/ugKT+OQEJH7ejIsnfnZTMaktK9HdVP0GdqEcPaIbzO0cBO5mGz/rbRZikkBQdYwxh4ZUl+B/cMjXedSUEg5rAAkh8dKvgPvg=="

file:
  dir: /root/image/
  url: "{cipher}AQAPrvQacIk1dSxbDUfMRHiYXwRtbG1l3mGcpj+pCZEpOf8UNBL1yR7RoiTX2CW9qy9pspTSPtwTo9bJzTiQ4ahoNovJnn4RPdaFOE7j5hD5bM58J++nxQIiyQyuaUw+78u/ewsaomGMZr3ljtl20iO15PjWj4QkaDq8e1tDVbLZ8I6CgDKTFE+eYi7gNgSEYGAodrnIdLMetW/xAa04+XM7wGmY3yVhJIc4N7MLlejgLDMG6sMqWF2ZV/9YegTA339EQ8srMK51hHdySDJTAQavdaYdMMvXZlWU0Y5j9oDrUW8z/xvwHBvs1WJz/BeCkF4sw81bJ/5yIiQ2SqPEdVjbdNfiX+qAT5iXNGcQCAPpTkXKd/eVldQCEBerrWJBD23VbdFAiQIZbxqL1XcEdw3G"

logging:
  level:
    com.wcd.clubservice: info

management:
  endpoints:
    web:
      exposure:
        include: health