spring:
  datasource:
    driverClassName: "{cipher}AQDaJ0YIo/sL3WXxItJLspRUPYBnKCX8gKxbWdv2OcOzOZvM+TzyFFZOzQxzYzcQ8oV/Sdqz5fdYbLYXjeBvm+dP3+YihKuzPsZP8xBinbc2MIwtR/LmqbQhdVyZfeeNiTSU3qZ8A/oPsh3K+1oeQmgoLKPcgyBixUq90K3bq7sdXzByK6rstdemtXqeUPJM+sF6LKzFLR6UTJKNL5h69J/3K1ITy4q8mPafIeVeS4kKqLCduJ0O4jfZXdFzsNms7jZ+Bdf3G+hejMLBrLIph+WZOB/4evJ1+apzYuT1V906aLD/SJVPwIBzIuo9NzEyoh06BloSkjUKAnqcecb2yr1fgTiE2zIRWZ3qPeQJUDoEaUS5kMsYw5giP+aHTcGSNwcKlmUucSJoSExk+wCv0wSB"
    url: "{cipher}AQC7RoqxYl25YwLY0HL7HdmvkxN3/gk2JxIkwWHyhlbRRLxgSb7uVJKrLcnML2LseWzJPLWP4LbfBJSz94EainaOSF9590lEOyHfuJFN4VDJITw9ZA8Ogivvmxo7iTQN1u/sf9U/wouStsMdRmO0QCxAmpcsbN+ZQwK3bWNymyTT0yPkt88y2Cc32+9wuS5w17A3/qt3m9AKN6egzqUxGP34ydZs2hmMWSOzHPXLZEt/LIZZ+EGjW+yQHtI4x6lqwsg+jBH9Z2jJTe+AxtkNKwM3VWinWGdDpxszuYFxVMTVVQoqnvjpN05Sp4CMSAqxOb8act6/YTn4y0FaTgspXOflIOK4gDPADfhCxtfBSLFLVGd35IoOi928XVjgYXb7AGUGTS0xA5c5fS4WxuTGu3CVhS2UYKwPQcTlImqkgYgrPQ=="
    username: "{cipher}AQAvVtEL1Wr/PonK0066xNu/KNjBrNRrJQ12Ka33wk98L3H9rxwh/x7RAvTGphK9VjjbIm7Aj1IrWHRJeDEvDQLVRUVJ1oIGqfcVUZt087HKlm5dugIqpeCONJK+FaubQTMO5/KKPPGMZEMuRle9ur2wIVmfm+0NNU0hk4nxD+lep201AzrKGUrdx7xHTT9AfTqtCSZaD5/aZgTfKCaIXxK2EWVYS+iOSFlNtAfv2L1qB5sZ0jqmKf3n4GJrxXEiZFB6dxMRDrieiuH8qesa89GXzGSfY6wT0aBRkUC0b1FXX3zR2wM9Dht+zT92D55gKfnn55MWX7vvN0xG7Y7bxOEgsz4MgLv1QQmbMo/BQr7E911C1vfEKlYXCQpWMPrXWi0="
    password: "{cipher}AQDc52o/8Yo707L1c2tGzMHylZxJYglyz8drR8nJ6kHQ7YVItGWFyQgySkoN2KIJFT6PzU35NTyktT2KpqTqf3KQRjAfqeFkCccxsWORZ5T6j6WHaPEaa0LK9zTssjtmK6wFfcryuXS7v4lr5SBgdaFxFc5rzfWZldy9QYzNGE7Mb/IaApQu7FxJGA3wfn2EQ9AIulZ0OMCYQmNOdmRtougXn7jtGy6CsPVNo/F1JziVage8M6pGwE/u/dG99Dr0WGEvPXWqou+m+dyofw8qRNwcJuxHPqsoRny+SLKNzob8P0iyOHrCx3/zGaSgY7pWzGy9t2n2cOTkRu8ZvlFeImcMUjrKxhOFdzcve1+TOtNZCit6IMMPfVOLdCD4JSK2WkQ="
  jpa:
    show-sql: true
    hibernate:
      # ddl-auto: update
      hbm2ddl.auto: update
    properties:
      hibernate:
        dialect: "{cipher}AQA9G+89tJBSbPFlGciphEBcNa5MpD66RAxy7lIBtEWDoSqIOY1IdXy8N+WTEcVItgg4Xk3UT5qRVnXngwn1e2BuezX4r3XXdVpZbz4TM77gwZ5cYPSTxqNImp18IhLUtko9WUexs0Nobcqu2ImYl8vW1OCLcblGSlaY8CSc/Z8C2OGQMhBFlV2vcX/45yZwWKRNyrN2GQyp+34X2S+cFgBxaZAqFpZYPaSCTpkfACyClgj7kXPHnDVwgl5ObBSYwYtaTDbsVbPq/xscjxwO7SauFllayzTQyVKuzby+Jmave7/srSblCcofB/K7MhnXqACdatzjkB6fK/ugKT+OQEJH7ejIsnfnZTMaktK9HdVP0GdqEcPaIbzO0cBO5mGz/rbRZikkBQdYwxh4ZUl+B/cMjXedSUEg5rAAkh8dKvgPvg=="

logging:
  level:
    com.example.schedule-service: INFO

management:
  endpoints:
    web:
      exposure:
        include: health