spring:
  datasource:
    driverClassName: "{cipher}AQDaJ0YIo/sL3WXxItJLspRUPYBnKCX8gKxbWdv2OcOzOZvM+TzyFFZOzQxzYzcQ8oV/Sdqz5fdYbLYXjeBvm+dP3+YihKuzPsZP8xBinbc2MIwtR/LmqbQhdVyZfeeNiTSU3qZ8A/oPsh3K+1oeQmgoLKPcgyBixUq90K3bq7sdXzByK6rstdemtXqeUPJM+sF6LKzFLR6UTJKNL5h69J/3K1ITy4q8mPafIeVeS4kKqLCduJ0O4jfZXdFzsNms7jZ+Bdf3G+hejMLBrLIph+WZOB/4evJ1+apzYuT1V906aLD/SJVPwIBzIuo9NzEyoh06BloSkjUKAnqcecb2yr1fgTiE2zIRWZ3qPeQJUDoEaUS5kMsYw5giP+aHTcGSNwcKlmUucSJoSExk+wCv0wSB"
    url: "{cipher}AQC7RoqxYl25YwLY0HL7HdmvkxN3/gk2JxIkwWHyhlbRRLxgSb7uVJKrLcnML2LseWzJPLWP4LbfBJSz94EainaOSF9590lEOyHfuJFN4VDJITw9ZA8Ogivvmxo7iTQN1u/sf9U/wouStsMdRmO0QCxAmpcsbN+ZQwK3bWNymyTT0yPkt88y2Cc32+9wuS5w17A3/qt3m9AKN6egzqUxGP34ydZs2hmMWSOzHPXLZEt/LIZZ+EGjW+yQHtI4x6lqwsg+jBH9Z2jJTe+AxtkNKwM3VWinWGdDpxszuYFxVMTVVQoqnvjpN05Sp4CMSAqxOb8act6/YTn4y0FaTgspXOflIOK4gDPADfhCxtfBSLFLVGd35IoOi928XVjgYXb7AGUGTS0xA5c5fS4WxuTGu3CVhS2UYKwPQcTlImqkgYgrPQ=="
    username: "{cipher}AQAvVtEL1Wr/PonK0066xNu/KNjBrNRrJQ12Ka33wk98L3H9rxwh/x7RAvTGphK9VjjbIm7Aj1IrWHRJeDEvDQLVRUVJ1oIGqfcVUZt087HKlm5dugIqpeCONJK+FaubQTMO5/KKPPGMZEMuRle9ur2wIVmfm+0NNU0hk4nxD+lep201AzrKGUrdx7xHTT9AfTqtCSZaD5/aZgTfKCaIXxK2EWVYS+iOSFlNtAfv2L1qB5sZ0jqmKf3n4GJrxXEiZFB6dxMRDrieiuH8qesa89GXzGSfY6wT0aBRkUC0b1FXX3zR2wM9Dht+zT92D55gKfnn55MWX7vvN0xG7Y7bxOEgsz4MgLv1QQmbMo/BQr7E911C1vfEKlYXCQpWMPrXWi0="
    password: "{cipher}AQBatMFoS7Gk8zeH/yDqh17exaCOb6vF9lk7H7/rhtCx05bdUBdbukeO1yk9ATSRg8qZciCY1aR/pDSVayqQmF1qrmXLFC4odwTlI/EGIvn1EiBefLbxrk+5WobAnC1bEKmxpYXBm4u7X/y7L/NE5SpKEAhL09py8tZv3IDIbsCK3NFACoUqb+G02nYSNnsI5shivkcElSW1TrIEiiTgQqioA/Drj8rXaWzgoDZ8SoRVZgeH4APNKooW3FMjkLvLEApFnFkR9IRPhUy77zQB/gwkd/3Xb+9igY2jAR1J1qO0u3Oe+yxtgvTTLBpk8tLsIFM0cpwG+vq+6w+x1NGLdhxrK+39BUMbod/WqWfN6TBRXi90B1Q8phI2BHOOeQaI+k4="
  jpa:
  show-sql: true
  hibernate:
    ddl-auto: update
  properties:
    hibernate:
      dialect: org.hibernate.dialect.H2Dialect

logging:
  level:
    com.example.schedule-service: INFO

management:
  endpoints:
    web:
      exposure:
        include: health