spring:
  datasource:
    driverClassName: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://10.1.1.24:3307/user_service
    username: root
#     password: "{cipher}AQBA9GCVlpL/WmvJWBc3nv0PiuCVcKqhT3+u5UXzvoh3WXBe5ji0+txmehR7HbfZAFSd0IVZu6j6Y8WUtx7RGYKBiqpeEuToSEtHWKT2I5WHLUM2O6MJP4SqHbSndjGA5JSUK8TJ+H9qpjPbwsXJWyEcy5nN+hlgtXqhIOPJKedddqC5qA3pTSf569SEmbm7CsxYFIyZjarlBTj+g4JoVecWwBp0LDmdLB1NhE7VCCLJeswtM6Y++mhXQPJe0maodL1uO0ZwGI7i4WrauwknmtY4Cq/m+MaWetE4EyeWl1MHIVpMKewxlc2xGi4XBH0e/g8H76k3snTaYPGM62fXZau2Hxqsb/671ZUTgO0a7qyt7jqSSIFtYONkL5zsx/hwy90="
    password: "{cipher}AQBatMFoS7Gk8zeH/yDqh17exaCOb6vF9lk7H7/rhtCx05bdUBdbukeO1yk9ATSRg8qZciCY1aR/pDSVayqQmF1qrmXLFC4odwTlI/EGIvn1EiBefLbxrk+5WobAnC1bEKmxpYXBm4u7X/y7L/NE5SpKEAhL09py8tZv3IDIbsCK3NFACoUqb+G02nYSNnsI5shivkcElSW1TrIEiiTgQqioA/Drj8rXaWzgoDZ8SoRVZgeH4APNKooW3FMjkLvLEApFnFkR9IRPhUy77zQB/gwkd/3Xb+9igY2jAR1J1qO0u3Oe+yxtgvTTLBpk8tLsIFM0cpwG+vq+6w+x1NGLdhxrK+39BUMbod/WqWfN6TBRXi90B1Q8phI2BHOOeQaI+k4="
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
  rabbitmq:
    host: "{cipher}AQBNnd9BIK7gKSQowRqpHUQs6KTtsViw906/56T1e58AovjAHiqcSWO/9fb0Bkt5wCbsAsUOBV5HW2RO8DiWLIzavGOvuMSttNXVdfYQaplEqOufYZe4G+SEMsPhHavat8dKRkka1pZb2YlXwQquC58LtZgwvsCBqXvrYb9R83N1cVrJa2xlO2TkR+6jA7gpCe5SW/IzY0WCQNJTgh8uXbddbXEB7kkL8pcTmxTvkZXLPgQw8LhBNPxOsPhK2z1nWmpd04Lxk91IUII43d4aWldrXGm7oa9dttfU70Sin5WLHywrqxc3E+4f3Y6HnYjDuUV/PMqbNZzJ/CSHC5yig0K5iF/rv2YKlWhQI6EsosRqyN0Dgl0PL58P+s5D6ECtWGQ="
    port: "{cipher}AQA6GSNzFqgXKQ+0V2JCgSRsDmfYu/f4WGh9cGY01rCzPvMOaOUPtC5e5zMD1lZTrljNKu7COQc1zZAXniQxobDkXYQM0pIY80+DydACc3VpU5SLWBS88PxF/qqjt03FVWSFaTaBnJ42rsKYjYiPl+LUidEo3jbO/U4/JAIFldlJ4Y5AY9PJ34qfJAo3fEUi1EJdR+o+Whiu2g03aEN1oz5k96HgY7mJsaP2k+5au9NT0Lj+QRCwwE8fr/P/M8X41VTvkuTz8q5jfu3PWomgbOH9PKRAXJKeH87qdG/vtQ0nccokw1+atoWM+Vn2aYYhLgwWppto7mpsnxhCSQJ4UB7D496UHnOxITigKH4uf+K5Pmole5u5lK8N1yMrp73WC7A="
    username: guest
    password: "{cipher}AQBAp8wk3XZDuSdXHs/j//HGyNvzHNrbSK7dG6khACfypYBWu438p9GC7m5acSdQq4yivtUNkZkcaGGzaxL6f2OD/WKLxU0cVnLrzM1M8UPvCevjicOzjJdmId7cxkg6yLCWj1ma/HVBg5rYu/Rqb70z/j9N00GIrv7Vpepg5AP12KA6c9pK26aOHiXsi/Hl8xZLy3WcYCU71YhHVsWdZGfKjPUHwC0T3YIXgvmuqeXKD1SdFppKhEBdMloabDey2GB+inmYVhBdZIntwJhKz88sFb2OyewarOzhvd0GDh8C0k28jT0gSqTZUjXEWoDqsEixXDVIYf7iMa65DhuNyW9KHV+s1dw4lFWdQcTXYgzdKzTFmR3uMASut0wzteINakw="

test:
  t1: test
