spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password:
# gateway:
#   ip:

access_token:
  expiration_time: 3600000
  secret: p2s5v8y/B?E(H+MbQeShVmYq3t6w9z$C&F)J@NcRfUjWnZr4u7x!A%D*G-KaP
  # 암호화
  # secret: "{cipher}"
  
refresh_token:
  expiration_time: 864000000
  secret: PeShVmYq3t6w9z$C&E)H@McQfTjWnZr4u7x!A%D*G-JaNdRgUkXp2s5v8y/B?E(H
