spring:
  datasource:
    driverClassName: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://10.1.1.24:3307/user_service
    username: root
    password: "{cipher}AQBatMFoS7Gk8zeH/yDqh17exaCOb6vF9lk7H7/rhtCx05bdUBdbukeO1yk9ATSRg8qZciCY1aR/pDSVayqQmF1qrmXLFC4odwTlI/EGIvn1EiBefLbxrk+5WobAnC1bEKmxpYXBm4u7X/y7L/NE5SpKEAhL09py8tZv3IDIbsCK3NFACoUqb+G02nYSNnsI5shivkcElSW1TrIEiiTgQqioA/Drj8rXaWzgoDZ8SoRVZgeH4APNKooW3FMjkLvLEApFnFkR9IRPhUy77zQB/gwkd/3Xb+9igY2jAR1J1qO0u3Oe+yxtgvTTLBpk8tLsIFM0cpwG+vq+6w+x1NGLdhxrK+39BUMbod/WqWfN6TBRXi90B1Q8phI2BHOOeQaI+k4="
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
  rabbitmq:
    host: 10.1.1.34
    port: 5672
    username: guest
    password: "{cipher}AQDPKO+lWahdZ50UWCUKlcA9GJi+XaGK8wTb3erXyoOl7qjSO16XK220RRY/UOomaxfFCFX1FnUI+nrQmFrNjhM7pvy0y7RTJwkclZnoiWu1AokpTgKy1bQWPyaLiL31I2RpH2m0jKXv3nNZsB/6KgQ2HCexE5x8dDRwA03rnKBcFofo+Zff9NFXmSTos5e4/p3Zhcyz6XFAgJmAo+PkJnH38xRFKemOMTvTufHC2qJIt37TwNP1cIG8Q0bC6MMttp1QzLdgJtO3Z/kquh6239cESe63ImCB3mZdKbuTG5NQ+MV3VVb4vRqy+1Nog2NhTMG0tRua5qJFFDdHnHczNShEogHbBoGU8oWDMLPJ6TjjdoITcgdO7i9vIcYSC/poG6U="

access_token:
  expiration_time: 3600000
  secret: "{cipher}AQA2Osc40D5OL07nyVPWgKHYdsPKvGpCftP0rWk1r/QENL9BNaoNolmsz4UwH9Rkrsgo7IGK+yhqlNB3HjyK7E68PeRHWWRRGNRLh3uCx8UZwMNghHBkOK7JUJgiI9bjLg7TYRH/GqvNjd9JzQHo+IE+pImar2NeJOZlaAuiqoYg3MiwxBVJtXuXkeyTHoJTFdsgwmZXDiOfHh9+jmdUCNkrgedmbC3E9gA0QzXYP5LTN5dnrgX+p/Q5bGKkTsNduAWPHxCQY08IvOEX6t13O9wyDKM2oxl55IjDVVkkAMElkYzF7wPzFRtsPKwLVYJTLifnDO9h4btAtq8H+7aimxixcHJYEiIKLS2bv8HO70SFlrDmgXCfikEVQPuDtdI1rHEM12qX1s/AC9FghxuUxmKwgXRtRwtSGH8j0QanBiUQTILr1RJKn0120I7Tm11ydFGEB85LkBKqPf35TdMfVeUq"
  
refresh_token:
  expiration_time: 864000000
  secret: "{cipher}AQCOSHnmMA7Q/Yak+19aIL1crEZnndXthEK105L9DwLF/O3ze8X1lwwa50rIN9fQmSCbEiE8mYp6HJ5AQKQwqH2x9iio9ecDXpE9kWTAVTSVvq7DaQY7NzFRCq/kScBwYX6p24HhsT4RMnOMztvw8oW7OkaeVM0ECGbe+Vwj8QwlLM/nIya2LQ/tBCArC7ECjvyU5+DJHhsSA9eMH4slFwcfMAc52xNZxznut4W4LjLHtGoskC0Dl3RRNPQTSxRjfSA2gONLFPGFttJIxykKprY/hXYd3XFsGvqKKSwBvlw61HMQRzL23yi+aoegWtOfRy8kN5guVOPRUgH6Hm4QY/jcUyKRaS268IlTm+g+01fyAX6t0n/bT6CzG6clbkmJLQflHNrrTKUu2JaumTOsL5fFRLffQ/gPLvRGR3Sk58RBY1aC0ilKJWOt0T/nXSXXFaj9ZSnNipYyvUjVqEUPA7YT"
  

test:
  t1: test
