spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:test
    username: sa
    password: 
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
      path: /h2-console
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: "{cipher}AQCtFTnP3qdXI8ds4+mmSlQNFCrx8JyTPh5Q2UT6ecOo3r36QJkQn/pwbyk43MUO4bF4XG4+8cnZPbIUNBp7GYTRDBnXybDxe6ESIl5DopShVnHonZ36PUTPkyFjAbGHzSoyTi8KFR6jPMlMCZfTyHksvB4LyduzZ1rcADfOY++IXhNgtK6rc0TBVJPC7wjM9N5DyG/obhOkMgJI2Q8m6GQtT0lwIRKSvWOySH8s7JR8grd4aXtgkb+CCOMjS8uXLR+HIHBJ11RtNptwjv8nuAbP7EuZRyu4Ma7qpivQtWnPGS+XwZ9845lswtTB70U7trDp5OjHrJ+Y0sM0jCVlFBwV5RyiMI+6TVpE4thIPStJnKGw3CJcCte3sAG6+r7QTcc="
  redis:
    host: 127.0.0.1
    port: 6379
  mail:
    host: "{cipher}AQBpNm/OzAE+KR0SNy2RVy1UCZP3OQacaIVeRhiZIRbbKhtPUtHcCfyzt3FqxagdAD9Myst58j1y2+buioOM7xyW7hDI7BjhKrT+37WksQUQFtyAgjsfR5Yb9u+ibDqJDEXp8HSgcKUd5GfbsjEP7uIw+qHn+hQTmDW+LHJZ+RZdHTWm0aPHODKo50tfaoBhQ1mi6GW9rtmBq2qY7wDKEfJHBVO4M9FKJju5LjYBYZ4obKZvP4BRZGJXX4H94VWasx0qRPazo6+6Lb51aimzPnN1rI2nyLg6A7Ytze01Lj2jhLuok4R7SZquDNV3zBARHmMQe2OlXP/T3ANP+amEcX9poxwHtKAkPW4u7jeq7JTTsOPmisOqUyyflhwVIgBLIV8="
    port: "{cipher}AQB/qsZ7ba+CehzsRbilAGbkUVsxNYWl3jleVqv1vMtNY038J/H3aKNATBMYpmcHCYgKeYT3UcPcRX5WSLsBWoXYrjnLJyLnZuMy4ejh3TiZiVEpFIA1I5ffEFrrMB34hSbU3V28n5uokSNMQArsplTPQ0j5RX4D9yFT7bzA6DhE5IkXL2AIy+1whOL8JTKrCJfc+GwfeaRoAPhMbIxB1+bjoVLfX9sA2cBvVRJIBqzTGZBOjAqCC+vrtoC3f+URmLf+vX/ikMoNsd9r4SwAJb/ZZOKAOmONaI28QTNE9eF5FLNOQQc+/kj98kgI1MJqGfAaw1I+e4btqaVVVUwI7n2QtRO1gLmLpzz+JecynOs65rlLyvF7pMYsaxoj0hxB7T8="
    username: "{cipher}AQAxsI7TcOJcBNZKj9Vcck+S0wtRsCFP1H/JF7DVx4n9S6tYWO1ltpj8Rri3RN68kDiiFVF7EQxE6I1mQFEUBlGgJZiSqO4xyFw7DJuIDTStf3mqqu0UytodCZchLDpdWXVcQqe3gLWd8kVmWJ5e2RgFCs4gOIZ8QyFvHq9Dzjvf1RXpQa1FaRflKt+VGwJ+gQ3/u7oGdtL/eIPwXshy1AjknZNIv/B0UiLKVsSMk0MsnUKnBsG2OEXyRgf7zyzwqPpEcpLxTAWJN8ca5aaq3c58c6iTKJhCk8eIBNzooiFIJXrqwSFVNdySlJZHFvawi9p7hLnYh5P2Maw/DG7TYPyg/vHujSHwhfM1tBq6ZcAjmlI/TQxR28JgMre6Dh+VXvieQe4PrHEKKMMCiOiffobY"
    personal: "{cipher}AQC4BvjLKvqWlFKBrLzv6M22uGLp7uQEP9kilAfp9JPDc37DeRLxdFxEVRVfCNwk8JP3jrKynYm9PzEYUdpghbun8qWSx1wd7ibCyi9woXMjkfFaEm62/u9x6CtjrGPL2HcaE4CEmSqQy5RHfgKJJvEcBRYYp0YnBSPTemXteb2X1zMVbK4kV9Jgv8d6cFW+lb7DQPOKPQ5qtKupcxJXHMHWrjUusZpu5/UZ3AuZZErK2uu3W25hyOHEO/oBwq7Y6HbwjnMC05O4egLVAGU90E4f0rb9l64aEwHanFQLywEcV5PbPbjxECMuED+gzw8hiBA2U5tCiEF/3moRd31+XiP26ZoV8g1D4ClWchqsx7LSq5wD9vmTHPmuDj51TNdeDAI="
    password: "{cipher}AQBtqw1Xu79vehB7diUR8NAuhjNPp+bgyLT8s1wK3bhEdz9d+dVqrjnIAFcAianW6HjB1j2tfEgBU7qSriHRkMbXsd04xBeC2/0JwoAkphMOyXEx0Ef6zYobZfODUqFEVMN5Sd/IHNw+/5PieYM0Zw7LnccMTMh33doUp7v6Bd1ybsWI0UyKzfCKJ7c/DHzPFvCRkfice+AcPdH1adjRdA+7IVlO9ekYH2pY5dv15LVKz+kp/7Hg5PlzdLB+14wU6va1Zogpty3SPNMZ1Q5BWE0EITWmRBwn/uDO23HKxNHwHW5STzMMNIlmlxn1o903A0sq8mlS1o4sT1fW/dE4dcty1Fif+/AYXdeoarQO0UMyeF4rClyw6hqOJx60NhIRvZnFLP90DX5eceSnqPwDGww5"
    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000
          starttls:
            enable: true
          transport:
            protocol: "{cipher}AQBbueRpOCbDFRLRaOlT+Qetu8LVjF2YDS0WcTXMqDCywO5fsuMm+VGI3sluzdTSO/E6zGENUC5Wiq/VVVj+46GbsFNJKAfGN3/7Fzx77N7AdW96F4f2UvO1doXZdDGKm08kKK35vFJGkvofFAyLyRpKtdXUK4wVxpnSFFHfeguUD9vGDTfshsmUVtJh40bihghjM5xawm21z65eGxViWguc5UhBeK0LHdXwW3QJbgHpXbV6q7ut2Lqji5OcnO4NmEqmdmNKfa8IOAC8kOJCXM9L9a1Jg2uxuHuyz5syUYV49CUGDz0VpEyfF0Y2UrJMV2UQsIPiCfF7tdnm9Ytxhy13VHhzOfNlSDJOZ1Fqew0LEq9t7Ds6xDmjAtzY7ogdfGk="
          ssl:
            enable: true
            trust: "{cipher}AQDgiHQ8rmrjA9m3jdr+xOlMm1qLhcz1lKC5gqf09L/49cCmtOerH2dJgcQioT58w1aep3wYl8AqN3CzEAu1KFoyd2U5Wuam/QqBO5lfbojX3wcg6zFh2GWPnPuSRGm7c525JhBETo9rWPJ7QbPGPcIMCoUzoD/vJxknNMN6c/D4kvnfMlxECIVg8ob4RjaWD4FxOcGLEkbuE3S4zzN89qKQweBb4wE9I4quQUcDeFp7x+5Ra1Izl5XFTP38FA7GN4pBDj76DXw1aKRLEUXaMFjwfL2fn+fjhXUirTMe73T0tipYbHfNz0gGGRpZliL7crSwSk3eW8KfgQRIcGFmkCjK2POHoFfExXKo44+nGVEtrKRsCb2ZhrdQ/JMBavFZsRA="
            protocols: "{cipher}AQCDSByl3LV3dGn5b4aS/YSY+5mxakAjCfIIdFqtWpyNVJuYol31/qZ52QtCS6JCrrn4/tlR8AUcgi++BK1MO/RvXOpQwPWFisN8f4etjwQWfGLkK+tBx/7FAaVnGHO/4SOQYCihdQOjLwkqlg2M4xaiWB/S1BOTo4kmEiD0LMr1P9E5JYICp0BC0NEO9Gt+MnsBzysCzU9YLTpH4LoVR2I1qsmhRXuCdBDBIXR8nU7ZpUqQzG8GtkpQs6B4m8dAbqDnFXo8DU1xkFVDW1jOn17qt/IurVo8eO0E8W8076Fpj9vQMOz6KWvbLii9oZLcpiLyhm0yv6sLAqUgVPP1+sM+7PtTFsxXfPZAePZl/e7VDaIMVF8/KyKfMcgkfRxWJrs="
        debug: true

file:
  dir: /image/
  url: http://211.115.222.246:1000/image/

management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans, busrefresh, httpexchanges, info, configprops, env