spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:test
    username: sa
    password: 
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        ddl-auto: create-drop
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
      path: /h2-console
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: "{cipher}AQCtFTnP3qdXI8ds4+mmSlQNFCrx8JyTPh5Q2UT6ecOo3r36QJkQn/pwbyk43MUO4bF4XG4+8cnZPbIUNBp7GYTRDBnXybDxe6ESIl5DopShVnHonZ36PUTPkyFjAbGHzSoyTi8KFR6jPMlMCZfTyHksvB4LyduzZ1rcADfOY++IXhNgtK6rc0TBVJPC7wjM9N5DyG/obhOkMgJI2Q8m6GQtT0lwIRKSvWOySH8s7JR8grd4aXtgkb+CCOMjS8uXLR+HIHBJ11RtNptwjv8nuAbP7EuZRyu4Ma7qpivQtWnPGS+XwZ9845lswtTB70U7trDp5OjHrJ+Y0sM0jCVlFBwV5RyiMI+6TVpE4thIPStJnKGw3CJcCte3sAG6+r7QTcc="
  redis:
    host: 127.0.0.1
    port: 6379

file:
  dir: /image/
  url: http://211.115.222.246:1000/image/

management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans, busrefresh, httpexchanges, info, configprops, env