# Spring Cloud Gateway? ???? API Gateway? ???? ?? ??
# Spring Gateway ???? Netty?? ??? ???? ?????.
# ?? ??
# Gateway Handler Mapping -> Predicate -> PreFilter -> ??? ?? -> PostFilter -> Gateway Handler Mapping

server:
  # API Gateway? ??? ? ?? ??
  port: 8000

eureka:
  # Eureka ????? ??
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      # Eureka Server? ??? ??
      defaultZone: http://localhost:8761/eureka

spring:
  # API Gateway ??? ?? ??
  application:
    name: apigateway-service
  # RabbitMQ? ???? ???? ???? ? ???? ??
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
  cloud:
    gateway:
      # ?? ???? ???? ??(Global ??)
      default-filters:
        - name: GlobalFilter
          args:
            baseMessage: Spring Cloud Gateway Global Filter
            # ?? ?? ?? ??? ????? ??
            preLogger: true
            postLogger: true
      # ??? ??
      routes:
        # ???? ??
        - id: user-service
          # ?? ??? ??? ??? ??? ??? ?? ??
          # Discovery(Eureka Server) ???? ?????? MicroService ???
          # user-service(?????? ??)? ??? ?? ?.
          uri: lb://USER-SERVICE
          # ??? ???? ?? ?? ??
          predicates:
            # client? POST /user-service/login? ???? uri ??? ???
            # login? ??? ?? Spring Security? ????? api
            - Path=/user-service/login
            - Method=POST
          # ??? ?? ??? ???? ??
          filters:
            # Cookie ??? ?? / Response Body? ?? ??? ??? ??, ??? Request Header? ??
            - RemoveRequestHeader=Cookie
            # ??? /user-service ?? ? user micro service ? ??
            # ?? ??? ??? ???? ?? ? ??
            - RewritePath=/user-service/(?<segment>.*), /$\{segment}
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/signup
            - Method=POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/user-service/(?<segment>.*), /$\{segment}
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/**
            - Method=GET, PATCH, DELETE
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/user-service/(?<segment>.*), /$\{segment}
            # ???, ????? ??? API?? JWT? ?? ??? ??? ??
            - AuthorizationHeaderFilter
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/actuator/**
            - Method=GET,POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/user-service/(?<segment>.*), /$\{segment}

# Actuator? ?????? ???? ??? ??
management:
  endpoint:
    web:
      exposure:
        include: refresh, health, beans, httptrace, busrefresh
