server:
  port: 5000

spring:
  application:
    name: openvidu

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka

openvidu:
  url: http://10.1.1.116:5443/
  secret: MY_SECRET

logging:
  level:
    com.wcd.openvidu: DEBUG